version: '3.1'

services:

  sosol-api:
    restart: always
    container_name: backend_sosol-api_1
    build: .
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - 7777:7777
    command: npm run dev
    env_file: .env

  postgres:
    image: postgres:12.4
    container_name: backend_postgres_1
    ports:
      - 5432:5432
    volumes:
      - .pgdata/db:/var/lib/postgresql
      - .pgdata/db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sosol_dev
    restart: unless-stopped

